# Generated by Django 5.2.8 on 2025-11-10 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('color', models.CharField(max_length=50, verbose_name='Масть')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('rating', models.IntegerField(default=1000, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер лицензии')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название забега')),
                ('scheduled_time', models.DateTimeField(verbose_name='Дата и время старта')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20)),
                ('distance', models.IntegerField(verbose_name='Дистанция (метры)')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Призовой фонд')),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.IntegerField(verbose_name='Номер дорожки')),
                ('win_odds', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Коэффициент на победу')),
                ('final_position', models.IntegerField(blank=True, null=True, verbose_name='Финальная позиция')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.horse', verbose_name='Лошадь')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.jockey', verbose_name='Жокей')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.race', verbose_name='Забег')),
            ],
            options={
                'unique_together': {('race', 'lane_number')},
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('win', 'На победу'), ('place', 'На попадание в призы (Топ-3)')], max_length=10, verbose_name='Тип ставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потенциальный выигрыш')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('race_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.raceparticipant', verbose_name='Участник забега')),
            ],
        ),
    ]
