# Generated by Django 5.2.8 on 2025-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceparticipant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='horse',
            name='color',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='rating',
        ),
        migrations.AddField(
            model_name='horse',
            name='breed',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('win', 'На победу'), ('place', 'На показ'), ('show', 'На третье место')], max_length=10, verbose_name='Тип ставки'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('won', 'Выиграла'), ('lost', 'Проиграла'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус ставки'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка лошади'),
        ),
        migrations.AlterField(
            model_name='race',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Призовой фонд'),
        ),
        migrations.AlterField(
            model_name='race',
            name='scheduled_time',
            field=models.DateTimeField(verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='raceparticipant',
            name='win_odds',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент на победу'),
        ),
        migrations.RemoveField(
            model_name='raceparticipant',
            name='final_position',
        ),
    ]
